const todoItem = [
  {
    id: 1,
    title: "Talk to Amir",
    date: "06-07-2021",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime nesciunt, dolorem ea voluptas voluptate consectetur eum eos id! Possimus",
    priority: "high",
    status: false,
  },
  {
    id: 2,
    title: "Go to Bank",
    date: "01-12-2021",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime nesciunt,",
    priority: "medium",
    status: false,
  },
  {
    id: 3,
    title: "Upwork task",
    date: "05-12-2021",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime nesciunt, voluptas voluptate consectetur eum eos id! Possimus",
    priority: "high",
    status: false,
  },
  {
    id: 4,
    title: "Fiver team work discussion",
    date: "22-12-2021",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime nesciunt, dolorem ea voluptas voluptate consectetur eum eos id! Possimus",
    priority: "low",
    status: false,
  },
  {
    id: 5,
    title: "Talk with mr shajeel",
    date: "05-11-2020",
    desc: "Possimus assumenda quo culpa illum et totam aliquam corporis doloribus excepturi",
    priority: "medium",
    status: false,
  },
  {
    id: 6,
    title: "Amir and Shahin meet",
    date: "06-12-2021",
    desc: "Lorem ipsum  adipisicing elit. Maxime nesciunt, dolorem ea voluptas voluptate consectetur eum eos id! Possimus",
    priority: "high",
    status: false,
  },
  {
    id: 7,
    title: "Visit coolors.co",
    date: "03-12-2021",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  dolorem ea voluptas voluptate consectetur eum eos id! Possimus",
    priority: "medium",
    status: true,
  },
];

export default todoItem;
